adata_path:
  - 

sample_names:
  - 

hto_list_per_sample: # Pay attention that the lenght of the list compatible to the sample_name list
  - 

demultiplex_method: demultiplex2 # hashsolo or demultiplex2

# Default: [negative probabiltity = 0.01, singlet probability = 0.8, doublet probability = 0.19]
# For hashsolo only
priors:     # Pay attention that the lenght of the list compatible to the sample_name list
  - [0.85,0.12,0.03]

  
